services:
  localstack:
    image: public.ecr.aws/localstack/localstack:3.8
    container_name: libumccr_localstack
    ports:
      - "4566:4566"
    volumes:
      - "./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
    environment:
      - DEBUG=1
